targetNamespace: ""
parameters: {}
environment:
  DB_URL: ${DB_URL}
  JWT_KEY: ${JWT_KEY}
packages:
  - name: auth
    environment: {}
    parameters: {}
    annotations: {}
    actions:
      - name: jwt
        binary: false
        main: "main"
        runtime: "go:default"
        web: true
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}
      - name: me
        binary: false
        main: "main"
        runtime: "go:default"
        web: true
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}
